@startuml latercera
skinparam  Style strictuml
skinparam  SequenceMessageAlignment center

class Ventas{
    - producto: string
    - precio: double
    - cantidad: int
    +ventas()
    +registroVentas()
}

class Almacen{
    - nombreEmpresa: string
    - direccion: string
    +ventas()
    +recibirPedido()
    +recibirPago()
}

class Pedido{
    - producto: Producto
    - cantidad: int
    - numeroDeSolicitud: int
    +recibirPedido()
    +registroPedido()
}

class Existencias{
    -producto: Producto
    -precio: double
    -cantidad: int
    +registroDeVentas()
    +existencias()
}

class Producto{
    -idProducto: int
    -nombre: string
    -precio: double
    -proveedor: Proveedor
    +asignacion()
    +retorno()
}

class Inventario{
    -numeroDeSolicitud: int
    +registroPedido()
    +existencias()
}

class Proveedor{}

Almacen-->Ventas: hace?
Almacen-->Pedido: toma?
Existencias-->Almacen
Existencias-->Producto
Inventario-->Pedido
Existencias--->Inventario
@enduml